### ISSUE TITLE
Allow arbitrary context to be passed through Larky execution

### ISSUE THREAD

**Issue by nestorsokil** [verygoodsecurity/starlarky#127]
## Problem or feature statement

When running Starlarky in production environment there is a need to persist system-level context that is set before the script's runtime and can be restored/accessed after and inside the different implementations of Larky-bound functions (such as Java's `@StarlarkMethod`. This context may also be accessible by the user, but then some keys have to private and immutable as they may carry system info non-relevant or dangerous for users to touch.

## Advised solution
It seems as the simplest approach would be to have the current context object contain private and immutable internal context. We will then have to make it part of the API for the methods that require it. It’s a similar pattern to what Go has which allows it to omit threadlocals.
https://golang.org/pkg/context/
So the script should look like:
```python
def process(ctx, in):
    card = find_card_in_payload(in)
    token = vault.put(ctx, card, format='PFTP')
```
A more complex way would be to implement annotation processor in the way that it injects this context into `@StarlarkMethod`s w/o users explicitly passing it. But as far as I can tell it would only cover Java extensions. While just having this explicit param will cover any runtimes and also eliminate any threading/synchronization issues.

## Testing scenarios
N/A (API design issue).

**Comment by mahmoudimus** [comment]
dupe of #128 ?
