### ISSUE TITLE
Porting asn1crypto library

### ISSUE THREAD

**Issue by 420neshot** [verygoodsecurity/starlarky#155]
## Problem or feature statement:
This is a request to port the complete `asn1crypto` library into Larky. The main purpose of this is using **Cryptographic Message Syntax (CMS, PKCS#7)** encryption algorithm which seems missing ATM and there are no alternatives.
## Advised solution:
The only solution is to do CMS, PKCS#7 encryption outside of VGS with the help of external tools.
## Customer requested:
Yes

**Comment by mahmoudimus** [comment]
Without a unittest to understand what is proposed to be ported, this issue is meaningless.
