### ISSUE TITLE
Create ECC object by importing public key 

### ISSUE THREAD

**Issue by alimariebaker** [verygoodsecurity/starlarky#169]
## Problem or feature statement

note: I think that implementing this module might not fully solve the ultimate problem. This might point us in the right direction of how to do the ECC encryption in python: https://cryptobook.nakov.com/asymmetric-key-ciphers/ecc-encryption-decryption

The Public Key ECC library is not functional: https://github.com/verygoodsecurity/starlarky/blob/master/larky/src/main/resources/vendor/Crypto/PublicKey/ECC.star

I need to create an ECC key with an ASCII/PEM public key string. 

ECC key generation:

```
from Crypto.PublicKey import ECC
from Crypto.Cipher import AES

public_pem = '-----BEGIN CERTIFICATE-----\nMIIEhzCCBC6gAwIBAgIIUNB2d+ldF7AwCgYIKoZIzj0EAwIwgYAxNDAyBgNVBAMMK0FwcGxlIFdvcmxkd2lkZSBEZXZlbG9wZXIgUmVsYXRpb25zIENBIC0gRzIxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzAeFw0yMTAyMTYxNDM4NDdaFw0yMzAzMTgxNDM4NDdaMIG5MS0wKwYKCZImiZPyLGQBAQwdbWVyY2hhbnQuY29tLnZlcnlnb29kc2VjdXJpdHkxQzBBBgNVBAMMOkFwcGxlIFBheSBQYXltZW50IFByb2Nlc3Npbmc6bWVyY2hhbnQuY29tLnZlcnlnb29kc2VjdXJpdHkxEzARBgNVBAsMCjQ0NDVZNjY0VTUxITAfBgNVBAoMGFZlcnkgR29vZCBTZWN1cml0eSwgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAReSfFJ7yTP9F0OXaZ7F4BFGPO2r88ZHd3TorwUJXPSSPBU/lHcNx8cAYxwXzxexxCIeMjljIO9KWc+jYEPpadlo4ICVTCCAlEwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBSEtoTMOoZichZZlOgao71I3zrfCzBHBggrBgEFBQcBAQQ7MDkwNwYIKwYBBQUHMAGGK2h0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDQtYXBwbGV3d2RyY2EyMDEwggEdBgNVHSAEggEUMIIBEDCCAQwGCSqGSIb3Y2QFATCB/jCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA2BggrBgEFBQcCARYqaHR0cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkvMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwuYXBwbGUuY29tL2FwcGxld3dkcmNhMi5jcmwwHQYDVR0OBBYEFK97iNuClYp1Q/uyEwjCPx4oDHVsMA4GA1UdDwEB/wQEAwIDKDBPBgkqhkiG92NkBiAEQgxAOEJEQkFCM0UxNTcwODhGOTQ5QTM3REZCODdENTgxNDBBQTNENTY2MUFGQTY2OTg3MEQ2Q0Q1QjBFNTZFQUQyMDAKBggqhkjOPQQDAgNHADBEAiBJB+R1GHAtE3N9uoY9emL7/DhR922zfQAZhEgRgk2edAIgLBB/9OIh3qdA2I7r/vJBeP8JwevDs56bFPtbwDsL8pY=\n-----END CERTIFICATE-----'

ecc_key = ECC.import_key(public_pem)

print(ecc_key.public_key())
# output:
# EccKey(curve='NIST P-256', point_x=42648052916686327210892301419955364834112034972971635650452863377521358656072, point_y=108705254063944462181308566815870444190317281276214355562320139479397481949029)
```

## Advised solution
pycryptodome ECC key + AES+GCM+nopadding cipher for the encryption

1. Import a public key in ASCII (PEM) format (this will be stored in the vault) to create the ECC object --(If we can also add the private key to it, that would be cool, but is not currently necessary so if it can only be partially implemented as MVP, that would be sufficient)--: https://pycryptodome.readthedocs.io/en/latest/src/public_key/ecc.html#Crypto.PublicKey.ECC.import_key 

2. We eventually need to create an AES+GCM+nopadding cipher: https://pycryptodome.readthedocs.io/en/latest/src/cipher/modern.html#gcm-mode

Resulting data should be able to be decrypted by the symmetric key here: https://github.com/verygoodsecurity/operation-pipeline/blob/master/operations/src/main/java/com/verygood/security/operation/util/pay/apple/ApplePay.java#L46

## Testing scenarios
- ecc key created by importing the public key
-  AES+GCM+nopadding cipher
- AES cipher can encrypt a message

I can provide test parameters if needed.

**Comment by mahmoudimus** [comment]
Fixed via #173
