### ISSUE TITLE
Write an explanation of the different repositories in this starlarky repo

### ISSUE THREAD

**Issue by mahmoudimus** [verygoodsecurity/starlarky#19]
- Explain how the syncing happens upstream
- Explain how `larky` depends on `libstarlark`
- Explain how the patches work on `libstarlark` and why they're needed
- Explain the general layout of the project and additions by VGS to create `Larky Script`

**Comment by mahmoudimus** [comment]
@blaisep-vgs @aslepakurov did this get resolved with #75 ?

**Comment by aslepakurov** [comment]
https://github.com/verygoodsecurity/starlarky#readme
