### ISSUE TITLE
Docker support broken

### ISSUE THREAD

**Issue by mjallday** [verygoodsecurity/starlarky#298]
## Problem or feature statement
Trying to use docker from README

`docker-compose build`

```
...
#0 92.41 done.
#0 92.41 done.
#0 92.53 update-alternatives: error: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java for java not registered; not setting
------
failed to solve: executor failed running [/bin/sh -c apt-get update -qq     && apt-get install -y curl openjdk-11-jdk maven     && update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java     && update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac     && apt-get install golang git -y     && go get -u github.com/tcnksm/ghr     && curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java11-linux-amd64-21.1.0.tar.gz -O -J -L     && tar xfz graalvm-ce-java11-linux-amd64-21.1.0.tar.gz     && mv graalvm-ce-java11-21.1.0 .graalvm     && rm graalvm-ce-java11-linux-amd64-21.1.0.tar.gz     && /build/.graalvm/bin/gu install native-image     && git clone https://github.com/pyenv/pyenv.git ~/.pyenv     && apt-get install -y gcc libbz2-dev libsqlite3-dev libssl-dev make zlib1g-dev libffi-dev     && ~/.pyenv/bin/pyenv install 3.8.6     && ~/.pyenv/bin/pyenv local 3.8.6     && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -]: exit code: 2
```

## Advised solution
Fix it or remove it. It appears there's a docker job in the circleci.yaml file but it's not invoked which is misleading. 

## Testing scenarios
`docker-compose build`

**Comment by mahmoudimus** [comment]
@mjallday I thought the whole point of docker is "works on my machine" isn't a problem any more but, I just tried it on my machine:

![image](https://user-images.githubusercontent.com/40820/171960982-2870165b-5882-4591-a02e-03a1b9161c3e.png)

Can you share more about your setup?

**Comment by mjallday** [comment]
windows 95, unpatched on a pentium 60 with 8mb of ram. 

docker 0.1 

<img width="215" alt="image" src="https://user-images.githubusercontent.com/252280/171963255-d7041ffb-a7ba-4f19-b827-cf86f6f0628d.png">

```
docker-compose --version
Docker Compose version 2.4.1
```

i'll give this a couple more tries locally since it's working for you. i see it's mounting `~/.m2` so it's probably that i don't have github authentication setup
