### ISSUE TITLE
Where do I see docs for all stdlib methods / properties?

### ISSUE THREAD

**Issue by mjallday** [verygoodsecurity/starlarky#44]
e.g. when i see 

```python
def process(input, ctx):
  util.foo(input.body)
```

where do i learn about `.body`, where do i learn about `util.foo`?

is there a naming convention that's used, if i wanted to suggest a new util method for inclusion how do i do that? is there a review process?

**Comment by blaisep-vgs** [comment]
maybe
https://starlarky-devel.readthedocs.io/en/latest/autoapi/pylarky/model/http_message/index.html
?

**Comment by mjallday** [comment]
That’s the docs _after_ the methods are written Blaise. I’m looking for the roadmap of utils well provide and the naming conventions we use to write them. 

I don’t want to have to constantly review the docs. I would prefer to see the proposed roadmap of functionality and how customers will interact. 

How do I make sure we don’t mix camel and snake case for instance?

**Comment by blaisep-vgs** [comment]
> I don’t want to have to constantly review the docs. I would prefer to see the proposed roadmap of functionality and how customers will interact.
> How do I make sure we don’t mix camel and snake case for instance?

I have it on good authority that @aslepakurov is the contact for larky grammar

**Comment by mjallday** [comment]
@aslepakurov can you help?

**Comment by mahmoudimus** [comment]
@mjallday is this the same as #62 ?

**Comment by mjallday** [comment]
yes, it's close enough that once #62 is complete my question is answered. 

#62 would need to include all future looking capabilities as well tho such as #50, and [everything else tagged `api`](https://github.com/verygoodsecurity/starlarky/issues?q=is%3Aissue+is%3Aopen+label%3Aapi).

**Comment by aslepakurov** [comment]
Docs is are already in works, including for stdlib
