### ISSUE TITLE
Remote call to access python package functionality 

### ISSUE THREAD

**Issue by viacheslav-fomin-main** [verygoodsecurity/starlarky#48]
Python has a great deal of already existing packages with pretty much everything you need. It would be great to have ability to use them. So here is my suggestion:

1. Create a python server with installed and imported a whitelisted set of python packages. 
2. Expose a grpc endpoint to invoke a package function by its name and parameters
3. Add a grpc client to starlarky functionality to make a call to this server whenever a python package is required. This call must be implicit so outside it looks like you run starlarky native utility function but under the hoot it is a grpc request.

As most of the code is usually a couple of method calls to some already written library, it should not add much of the latency.

**Comment by blaisep-vgs** [comment]
FWIW, this project has a lot of tests that we might be able to leverage:
https://github.com/danielgtaylor/python-betterproto/tree/master/tests/inputs

**Comment by mahmoudimus** [comment]
I am not in favor of this proposal, it seems to me that it would introduce risk and security vectors. Presumably, we would maintain a whitelist, but as of right now, I wonder if this is similar to what @mjallday proposed to #49 ?

**Comment by aslepakurov** [comment]
We dicided on no external dependency calls for Larky, would revisit on #49
