### ISSUE TITLE
Port stdlib package re from Python

### ISSUE THREAD

**Issue by nicasioca** [verygoodsecurity/starlarky#51]
Port the standard library for regular expressions from Python [https://github.com/python/cpython/blob/3.9/Lib/re.py](https://github.com/python/cpython/blob/3.9/Lib/re.py), like was done for the requests package [https://github.com/verygoodsecurity/starlarky/blob/master/larky/src/main/resources/stdlib/urllib/request.star](https://github.com/verygoodsecurity/starlarky/blob/master/larky/src/main/resources/stdlib/urllib/request.star).

I'm assuming it would be part of "starlarky/larky/src/main/resources/stdlib/" ([https://github.com/verygoodsecurity/starlarky/tree/master/larky/src/main/resources/stdlib](https://github.com/verygoodsecurity/starlarky/tree/master/larky/src/main/resources/stdlib)).

**Comment by nicasioca** [comment]
I pushed the customer expectation out to next week, so beginning of March sometime. Thanks!

**Comment by mahmoudimus** [comment]
@nicasioca - please check #55 to see if this solves your problem.
