### ISSUE TITLE
Publish larky java lib as a part of release CI process

### ISSUE THREAD

**Issue by Agitolyev** [verygoodsecurity/starlarky#52]
Starlarky project release CI should include a step for publishing `libstarlark` and `larky` java libraries to artifactory, to keep consistent versioning with other release artifacts, and eliminate manual releases.

**Comment by mahmoudimus** [comment]
@aslepakurov did you fix this with #72 ?

**Comment by aslepakurov** [comment]
Releases can be found [here](https://github.com/orgs/verygoodsecurity/packages?repo_name=starlarky). Address circleci config for distribution implementation
