### ISSUE TITLE
ISO8583 support

### ISSUE THREAD

**Issue by fshaikh-vgs** [verygoodsecurity/starlarky#99]
## Problem or feature statement
I would like to be able to modify ISO8583 objects using larky.

## Advised solution
I would like to be able to send to Larky a packager config and bytes(?) of data.  Larky should then use the packager to parse the data into a format that can be manipulated and then re-pack the data for upstream use.

https://github.com/jpos/jPOS/blob/master/jpos/src/main/java/org/jpos/iso/ISOBasePackager.java

## Testing scenarios
TBD

**Comment by aslepakurov** [comment]
https://github.com/verygoodsecurity/starlarky/pull/112
